[tool.poetry]
name = "hotel-service"
version = "0.1.0"
description = "Hotel booking API"
authors = ["Stanislav"]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = ">=3.11,<4.0"
django = ">=5.2.7,<6.0.0"
djangorestframework = ">=3.16.1,<4.0.0"
psycopg2-binary = ">=2.9.11,<3.0.0"
python-dotenv = ">=1.2.1,<2.0.0"
drf-spectacular = ">=0.29.0,<0.30.0"
drf-yasg = ">=1.21.11,<2.0.0"
djangorestframework-simplejwt = ">=5.5.1,<6.0.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.14.3"
pre-commit = "^4.3.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
lint.extend-select = ["I"]
lint.select = ["E", "F", "I"]
lint.ignore = ["E501"]
target-version = "py311"
