name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: hotel_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB: hotel_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_TEST_DB: hotel_test
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONPATH: src

      #Django
      DJANGO_DEBUG: False
      DJANGO_SECRET_KEY: ci-test-secret
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run Ruff (lint)
        run: |
          poetry run ruff check .

      - name: Run Ruff formatter check
        run: |
          poetry run ruff format --check .

      - name: Run migrations
        run: |
          cd src
          poetry run python manage.py migrate --noinput

      - name: Run tests
        run: |
          cd src
          poetry run pytest --disable-warnings --maxfail=1
